### ISSUE TITLE
issue in nextjs while running the application - getting error of react query mutation

### ISSUE THREAD

**Issue by Nabwin** [ferdiunal/refine-admin#2]
![image](https://github.com/user-attachments/assets/19a3f7b3-7d49-41d4-98b1-818165b3aeab)

TypeError: this[#client].defaultMutationOptions is not a function

**Comment by ferdiunal** [comment]
Hi @Nabwin, can you give me some details about the code etc. you are using so that I can help you more easily? You can take reference from the [Next.js](https://github.com/ferdiunal/refine-shadcn/tree/main/templates/nextjs) example.

**Comment by Nabwin** [comment]
> Hi @Nabwin, can you give me some details about the code etc. you are using so that I can help you more easily? You can take reference from the [Next.js](https://github.com/ferdiunal/refine-shadcn/tree/main/templates/nextjs) example.

the templates you have provided for nextjs doenot work can you run it in your machine it doesnot work in any of the pages except dashboard pages .

**Comment by ferdiunal** [comment]
Examples of all templates are working in vercel. As far as I understand, the problem is not related to the package. If you think you are getting an error with the package, please give me details and I can help you.
